//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilingHelper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class AddinSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AddinSettings defaultInstance = ((AddinSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AddinSettings())));
        
        public static AddinSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EmailSignatureInternalNew {
            get {
                return ((string)(this["EmailSignatureInternalNew"]));
            }
            set {
                this["EmailSignatureInternalNew"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InternalDomainNames {
            get {
                return ((string)(this["InternalDomainNames"]));
            }
            set {
                this["InternalDomainNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9437184")]
        public int MaximumEmailSizeBytes {
            get {
                return ((int)(this["MaximumEmailSizeBytes"]));
            }
            set {
                this["MaximumEmailSizeBytes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EmailSignatureInternalReply {
            get {
                return ((string)(this["EmailSignatureInternalReply"]));
            }
            set {
                this["EmailSignatureInternalReply"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EmailSignatureExternalNew {
            get {
                return ((string)(this["EmailSignatureExternalNew"]));
            }
            set {
                this["EmailSignatureExternalNew"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EmailSignatureExternalReply {
            get {
                return ((string)(this["EmailSignatureExternalReply"]));
            }
            set {
                this["EmailSignatureExternalReply"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EmailSignatureEnabled {
            get {
                return ((bool)(this["EmailSignatureEnabled"]));
            }
            set {
                this["EmailSignatureEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int FolderHistoryMaxItems {
            get {
                return ((int)(this["FolderHistoryMaxItems"]));
            }
            set {
                this["FolderHistoryMaxItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FolderHistoryPersistVisible {
            get {
                return ((bool)(this["FolderHistoryPersistVisible"]));
            }
            set {
                this["FolderHistoryPersistVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FolderHistoryAvoidVisible {
            get {
                return ((bool)(this["FolderHistoryAvoidVisible"]));
            }
            set {
                this["FolderHistoryAvoidVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int MailHistoryMaxItems {
            get {
                return ((int)(this["MailHistoryMaxItems"]));
            }
            set {
                this["MailHistoryMaxItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AttachmentHelperAutoShow {
            get {
                return ((bool)(this["AttachmentHelperAutoShow"]));
            }
            set {
                this["AttachmentHelperAutoShow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AttachmentHelperAutoHide {
            get {
                return ((bool)(this["AttachmentHelperAutoHide"]));
            }
            set {
                this["AttachmentHelperAutoHide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9000000")]
        public int AttachmentHelperMaxEmailSize {
            get {
                return ((int)(this["AttachmentHelperMaxEmailSize"]));
            }
            set {
                this["AttachmentHelperMaxEmailSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>FW:</string>\r\n  <string>RE:</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection EmailSignatureReplyForwardPrefix {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["EmailSignatureReplyForwardPrefix"]));
            }
            set {
                this["EmailSignatureReplyForwardPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ExplorerSelectionChange")]
        public global::HelperUtils.MailHistoryAddMode MailHistoryAddMode {
            get {
                return ((global::HelperUtils.MailHistoryAddMode)(this["MailHistoryAddMode"]));
            }
            set {
                this["MailHistoryAddMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection SuggestionExcludedFolders {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SuggestionExcludedFolders"]));
            }
            set {
                this["SuggestionExcludedFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SuggestionMenuSender {
            get {
                return ((bool)(this["SuggestionMenuSender"]));
            }
            set {
                this["SuggestionMenuSender"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SuggestionMenuConversation {
            get {
                return ((bool)(this["SuggestionMenuConversation"]));
            }
            set {
                this["SuggestionMenuConversation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SuggestionMenuHistory {
            get {
                return ((bool)(this["SuggestionMenuHistory"]));
            }
            set {
                this["SuggestionMenuHistory"] = value;
            }
        }
    }
}
